development:
  sessions:
    default:
      database: billbo_dev
      hosts:
        - localhost

test:
  sessions:
    default:
      uri: <%= ENV['MONGO_TST_URI'] %>

production:
  sessions:
    default:
      uri: <%= ENV['MONGO_PX_URI'] %>
